### ISSUE TITLE
Open in AnkiHub text - option to hide

### ISSUE THREAD

**Issue by PavloKr** [AnKingMed/AnKing-Note-Types#100]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```

#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*

Windows 10, iOS (mobile)

#### Problem case

*Is your feature request related to a problem? If so, please describe it here.  E.g.: "My workflow is such and such, and this and that would help."* 

There is no way to disable or shrink the "open in AnkiHub" text at the bottom of every card on Anking V12. This leads to accidental taps on this link when answering cards on mobile, disrupting workflow. 

#### Solution

*Concisely describe the solution you would like*

Offer option to hide "open in AnkiHub" text like what is possible using Anki Note Types Addon with current fields (i.e. hide tags)

Alternatively, please make this text much smaller if not possible to hide. It is massive on mobile. Thank you!

*Concisely describe alternatives you've considered (if any)*

Tried removing with code. Comes back after syncing with AnkiHub.

#### More information

*Additional context: Add any other context or screenshots about the feature request here.*

**Comment by AnKingMed** [comment]
You can actually modify it in the note styling however you want. The html class is `ankihub`

You could also change the back template piece (at the very bottom) to:
```
<!-- BEGIN ANKIHUB MODFICATIONS --><br><br>
{{#ankihub_id}}<details><summary>AnkiHub</summary>
<a class='ankihub' href='https://app.ankihub.net/decks/notes/{{ankihub_id}}'>
View Note on AnkiHub
</a>
{{/ankihub_id}}</details>
<br><!-- END ANKIHUB MODFICATIONS -->
```

**Comment by PavloKr** [comment]
Thank you, resolved!
