### ISSUE TITLE
Unable to update note types

### ISSUE THREAD

**Issue by chartranzudo** [AnKingMed/AnKing-Note-Types#103]
#### Which Note Type (and version) is this about?
Was trying to update the general note type after the new update of this add-on (2022-12-22) but get an error message from Anki.

#### Problem description

I edited the TTS section of the general note type (just changed playback speed) and pressed the "Update Notetypes" button. I got an error message from Anki pasted further down.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.55
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

MacOS Ventura 13.1

#### Error message (if any)

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 6.3.2 PyQt 6.3.1
Platform: macOS-13.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-12-21 21:29:17
Add-ons possibly involved: ⁨AnKing Note Types Easy Customization⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "/Users/*MyUsername*/Library/Application Support/Anki2/addons21/952691989/gui/config_window.py", line 410, in on_done
    mw.col.models.update_dict(model)  # type: ignore
  File "anki.models", line 223, in update_dict
  File "anki._backend_generated", line 883, in update_notetype_legacy
  File "anki._backend", line 148, in _run_command
anki.errors.CardTypeError: Card template ⁨1⁩ in notetype '⁨Basic-AnKing⁩' has a problem.<br>See the preview for more information.

```

```

**Comment by AnKingMed** [comment]
@RisingOrange can you look into this?

**Comment by RisingOrange** [comment]
@chartranzudo Can you try to reset the note type from its tab in the AnKing note types menu? This will probably solve the issue.

**Comment by chartranzudo** [comment]
That worked to stop getting the error message yes. But if I try to update the TTS in the general tab I get the same error again. I was able to enable TTS on just the card type I was using (AnkingOverhaul), but now instead of reading the whole front of the card it just say "dot" i.e. reading the [...] from the cloze but not the rest of the front. Back of cards are read normally.

**Comment by RisingOrange** [comment]
@chartranzudo There is a new version of the add-on on AnkiWeb that fixes these issues.

**Comment by chartranzudo** [comment]
The new version fixed these bugs, thanks!

**Comment by RisingOrange** [comment]
@chartranzudo Great!
