### ISSUE TITLE
Image Size Too Small after updating to 2.1.55

### ISSUE THREAD

**Issue by gabrielpacosta** [AnKingMed/AnKing-Note-Types#104]
IO-one-by-one , last version

Whenever I paste an image and try to create an IO-one-by-one card, the image has this size, which is too small and does not allow me to create the occlusion boxes properly.
I already tried to disable all other add-ons.

![image](https://user-images.githubusercontent.com/20757459/209241131-77e35915-38c5-49bb-889b-d0b77cb1d0ee.png)

Version ⁨2.1.55 (01caec2a)⁩
Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Windows 10

**Comment by RisingOrange** [comment]
@gabrielpacosta Double-clicking the image should toggle it to it's default size.

**Comment by gabrielpacosta** [comment]
> @gabrielpacosta Double-clicking the image should toggle it to it's default size.

I already tried and nothing changed

**Comment by AnKingMed** [comment]
Does double clicking the image do anything? Does it resize the image to full size?

**Comment by gabrielpacosta** [comment]
No, check the two prints showing how it changes after double clicking
![image](https://user-images.githubusercontent.com/20757459/209255268-7e6674ca-88c6-4909-876e-8e9d9d7e8200.png)
![image](https://user-images.githubusercontent.com/20757459/209255307-c1b99f2b-d1fa-4c19-ba6d-691280c38838.png)

**Comment by AnKingMed** [comment]
I just tested and the note type is definitely working for me on 2.1.55 Qt6. Can you try without any add-ons enabled with a new image?

**Comment by gabrielpacosta** [comment]
> I just tested and the note type is definitely working for me on 2.1.55 Qt6. Can you try without any add-ons enabled with a new image?

I updated to Qt6 and it worked. The problem was with Qt5. I tried with no addons on both versions. The issue persists for Qt5 version.
Thanks

**Comment by AnKingMed** [comment]
Glad you fixed it
