### ISSUE TITLE
Hide fields not working

### ISSUE THREAD

**Issue by dalton264** [AnKingMed/AnKing-Note-Types#108]
#### Which Note Type (and version) is this about?
anking overhaul but same issue with other note types as well. I redownloaded the addon so im assuming most current  
#### Problem description

I am trying to use the anking overhaul note type. I tried to disable some of the fields but when I go to the note type the fields are still present. I tried disabling all addons except for the note type and closet addon, I also tried re-downloading the addon but nothing worked. 

If all else fails what do I need to change in the code to disable these fields myself? 
![image](https://user-images.githubusercontent.com/121759060/212377123-4a97b252-bdf4-4970-b887-b96831e5a0ea.png)
![image](https://user-images.githubusercontent.com/121759060/212377214-1227dc33-82c9-4acd-a56a-6503ec267528.png)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
 ⁨2.1.56 q5
Didnt work on older version as well tho 
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*
Windows 

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*
no error message 

```

```

**Comment by AnKingMed** [comment]
I'm not able to replicate this on my end. When you go to the card styling, what version do you have at the top? (see my highlight)

![image](https://user-images.githubusercontent.com/57678116/212444940-a5805e9b-6926-46d6-bd5c-8e3c681fe804.png)

**Comment by dalton264** [comment]
I checked and I am on version a31e833

**Comment by AnKingMed** [comment]
I think I realized the issue. Do you mean the note fields are still in the editor?  That only hides them from the reviewer

**Comment by dalton264** [comment]
yes thats what I was thinking thanks for the clarification!
