### ISSUE TITLE
I can't get cloze one by one

### ISSUE THREAD

**Issue by navakelvin** [AnKingMed/AnKing-Note-Types#109]
#### Which Note Type (and version) is this about?
Close one by one

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.
 - [x] I've read through the README documents on this github and/or watched the tutorial video on the note types

#### What Anki version are you using?

```
2.1.56 Qt6
```

#### Your question
I can't get the note type cloze one by one. I have installed the Note Types plugin and used the update function of the plugin.

I get all the notes except Cloze one by one. I do not know what I'm doing wrong.

On the plugin page it says this but I've tried several types of Anking note and they don't work or look like the image.

![image](https://user-images.githubusercontent.com/77164639/212445600-20debd13-afa5-4256-a803-60feb6ac9b93.png)

**Comment by AnKingMed** [comment]
Watch this video and let me know if it's still not working:  The AnKing Note Types and Add-on: https://youtu.be/NYUhNMyAZNs

**Comment by navakelvin** [comment]
What a detail I was skipping, "y". Thank you very much for your help and patience Sir.
