### ISSUE TITLE
Auto-reveal first cloze

### ISSUE THREAD

**Issue by akavi1** [AnKingMed/AnKing-Note-Types#22]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using? - 2.1.44

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.44
```

#### Your question

I loved how in the older version of the cloze one-by-one 2.1 (the version that came with v10), the first cloze was revealed automatically upon flipping to the back. This let me use the one-by-one for cards that have only 1 deletion and cards with more than 1 without any additional key presses. Is there a way to do this with the new one-by-one note type?

Alternatively, is there a way to use a single shortcut to both unveil the next cloze and mark a card "good" if all clozes are revealed?  This plus autoflip would also solve the problem.

Thank You

**Comment by AnKingMed** [comment]
Yes, the new one by one features in the notes lets you autoflip the cards. I am still working on them and they're very much in alpha phase. I'm planning on beta testing on patreon for a few weeks and then releasing it publicly along with a video that explains all the features.
