### ISSUE TITLE
about IO one by one and anking notetype

### ISSUE THREAD

**Issue by ankibhavesh** [AnKingMed/AnKing-Note-Types#30]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Your question
![image](https://user-images.githubusercontent.com/96439843/147151953-5bdc33c0-189c-4fa5-8379-a5dd04f13ac3.png)
all the tags are seen below while studying card ...its becomes bit annoying...any solution hide those tage
*A clear and concise question about the note type.*

**Comment by AnKingMed** [comment]
It's under **Clickable tags** on the home readme.  It's also in the tutorial video
