### ISSUE TITLE
Cannot change the color of the "Back" in the Basic-type notes.

### ISSUE THREAD

**Issue by Farinata** [AnKingMed/AnKing-Note-Types#33]
Cannot change the color of "Back" in the Basic-type notes. It is only white or black (dependent on night mode option).

In the styling color part there is this line

```
/* Cloze Color */

.cloze {

color: blue;
```

Which I think there is a mistake, should not be "Cloze" ?

How to fix this? An how to change the color of Back?

**Comment by RisingOrange** [comment]
Thanks for reporting! This should work correctly in the newest update.

**Comment by Farinata** [comment]
Dears, 
Still have this problem even with the new updates. 
The color of the back in basic types is set to blue by default. 
But still it is white or black depending on night mode, and I cannot change it to any color.
