### ISSUE TITLE
One by One cloze

### ISSUE THREAD

**Issue by djm433** [AnKingMed/AnKing-Note-Types#35]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've checked if anyone else asked this question before by looking through the issue reports.
 - [ x] I've read through the README documents on this github and/or watched the tutorial video on the note types

#### What Anki version are you using? 

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.49
```

#### Your question

I am very interested in using the "one by one" cloze function, but I can't figure out how to use this function on the existing AnKing cards. It is available when I go to add a card, but the section doesn't appear when I try to use it on existing cards. Please help.

**Comment by AnKingMed** [comment]
You just need to change the AnKingMaster-v3 note types in your collection to the new AnKingOverhaul note type:  Anki: How to Change Note Types (for the AnKing Overhaul): https://www.youtube.com/watch?v=vOvz_aWEK48
