### ISSUE TITLE
Text to speech not working

### ISSUE THREAD

**Issue by CMBanks25** [AnKingMed/AnKing-Note-Types#37]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x ] I've checked if anyone else asked this question before by looking through the issue reports.
 - [x ] I've read through the README documents on this github and/or watched the tutorial video on the note types

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.49
```

#### Your question

*The text-to-speech speed is only working on the front. I have set both the front & back to 2.80 and only the front speech is sped up. I am working on mac. *

**Comment by AnKingMed** [comment]
Is this just the AnKingOverhaul note? Or others too?

**Comment by CMBanks25** [comment]
It occurs on both the AnkingOverhaul note & the Anking note type. I have not tested other note type as mainly use AnkingOverhaul note

**Comment by AnKingMed** [comment]
Mine is definitely working on the AnKingOverhaul note type. It's set to only read the cloze. Are you not hearing that at all?
