### ISSUE TITLE
Tags Container Preferences Not Saving

### ISSUE THREAD

**Issue by rtintalebi** [AnKingMed/AnKing-Note-Types#39]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Toggling "Tags Container" on the Anking Note Types Add-on and then clicking "Save" does not save the change, so no tags are shown

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

Version 2.1.49

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.49
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*
MacOS 10.13.6

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by rtintalebi** [comment]
Issue Resolves if CSS is manually edited in Card Styling

**Comment by RisingOrange** [comment]
This was fixed in the last update of the add-on.
