### ISSUE TITLE
Prevent 'Scroll to button when toggled' feature from jumping to hints set to auto-reveal

### ISSUE THREAD

**Issue by MightyBooman** [AnKingMed/AnKing-Note-Types#40]
#### Which Note Type (and version) is this about?
I've only noticed with AnkingOverhaul.
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.49
```

#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Catalina v10.15.7

#### Problem case

I like to have FirstAid hint section auto-reveal. However, when I select 'scroll to button when toggled' from the 'General' section of the addon, then the back of the card will immediately scroll to FirstAid, if available. I only want the back of the card to scroll to the hint section when I toggle a new hint with 'h' key. 

I believe that this is only a problem with the new Anking note types. Before downloading, I could edit the styling of the note type such that the FirstAid hint would auto-reveal, and scrolling would automatically occur when toggling with 'h' key.

#### Solution

*Concisely describe the solution you would like*
Prevent auto-scrolling to hint section upon flipping the card for hints that are set to auto-reveal. Only scroll to hints that are manually toggled open.

*Concisely describe alternatives you've considered (if any)*
n/a

#### More information

*Additional context: Add any other context or screenshots about the feature request here.*
n/a

**Comment by AnKingMed** [comment]
This may be because of how we changed the button code. @RisingOrange do you have any insight into this?

**Comment by RisingOrange** [comment]
I added a commit that addresses this to my latest PR:
 https://github.com/AnKingMed/AnKing-Note-Types/pull/41
