### ISSUE TITLE
TTS, hint hotkeys incompatibility

### ISSUE THREAD

**Issue by AnKingMed** [AnKingMed/AnKing-Note-Types#44]
The tts on the AnKing note types should be like this

Instead of 
{{tts en_US voices=Apple_Samantha speed=1.7:cloze:Text}} for tts and hint hotkeys to work. 

Otherwise it makes it so “H” cannot reveal hints it just replays the audio instead.

@RisingOrange Should we look into adjusting the hint hotkeys add-on? Or just code our own shortcut that works for every button?

Not urgent, but something to consider

**Comment by RisingOrange** [comment]
I think it might be best to make our own shortcut. What should the the default key be?

**Comment by AnKingMed** [comment]
Ideally 'H'... but would that still work with the hint hotkeys add-on?

**Comment by RisingOrange** [comment]
Yes, I can remove the code that made it work with the hint hotkeys add-on in the first place (and add the shortcut to the note type).

**Comment by AnKingMed** [comment]
That would probably be best if that's not too difficult, then it won't conflict with TTS and it will allow users to easily change the key
