### ISSUE TITLE
Mathjax code error

### ISSUE THREAD

**Issue by Stat-Shiwoo** [AnKingMed/AnKing-Note-Types#47]
#### Which Note Type (and version) is this about?
AnKing (version 36bc04b)

#### Problem description
Mathjax code doesn't work on cloze.
https://ibb.co/C2M10V9
https://ibb.co/yP4jnC1
https://ibb.co/fd0k2gD

I have tried two types of cloze on equations;
inside mathjax inline code and outside it.
The latter one seems to work on AnKing note, but transforming codes into math equations doesn't work at all.
This only happens when "one by one" field is filled with "y".
If the field is empty, the transformation works well.

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [**x**] I've restarted Anki to see if it helps
 - [**x**] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [**x**] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [**x**] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
Version ⁨2.1.49 (dc80804a)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Windows 10
*Please include OS version as well if possible*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by RisingOrange** [comment]
This has been solved (https://github.com/AnKingMed/AnKing-Note-Types/commit/5e81c28752b5d346b6bf149889fa7be1efd2300f) and the new note type version containing the fix will be released soon.

**Comment by RisingOrange** [comment]
Mathjax code should work correctly on one-by-one cards now.

**Comment by Stat-Shiwoo** [comment]
> 

Still it doens't work. I already confirmed that I am using the latest version of Anking note type add-on. Am I wrong? Do I have to do something??

**Comment by RisingOrange** [comment]
Have you updated the note types? You have to open the add-ons window (Anki's main window -> AnKing -> Note types -> Update note types)

**Comment by Stat-Shiwoo** [comment]
I get it. I updated as you said. Now it works well ! Thanks ! I appreciate it !
