### ISSUE TITLE
Hotkey for Flipping Cloze 1 by 1 Does Not Work

### ISSUE THREAD

**Issue by dragonbookreader** [AnKingMed/AnKing-Note-Types#51]
#### Which Note Type (and version) is this about?
 Anking Basic

#### Problem description
The hot key to flip cloze one by one doesn't work at all. If I click on the button to flip the individual cloze, it will, but no shortcuts on my keyboard. I tried changing it from n to other letters/numbers to see if it would help. It did not. I edited it in both the card field and using the add on, but neither worked. I have never used this card type before and was testing it out, so I didn't edit it before this. 

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ x] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.49
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
Windows
*Please include OS version as well if possible*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by RisingOrange** [comment]
You can try if resetting the note type from the AnKing Note Types window helps.

**Comment by dragonbookreader** [comment]
I had the wrong note type that explains it. Thank you for the help!
