### ISSUE TITLE
IO-one by one

### ISSUE THREAD

**Issue by jaredagordon** [AnKingMed/AnKing-Note-Types#52]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've checked if anyone else asked this question before by looking through the issue reports.
 - [ ] I've read through the README documents on this github and/or watched the tutorial video on the note types

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Your question

*Is there a shortcut key to duplicate an occlusion? Like the OG I/O note template (I believe it was 'D').*

**Comment by AnKingMed** [comment]
No there isn't any way to do that as far as I'm aware. That would be determined by the Closet addon, not this note type
