### ISSUE TITLE
Can I make height of images appear fully on the screen in AnKing note type?

### ISSUE THREAD

**Issue by Stat-Shiwoo** [AnKingMed/AnKing-Note-Types#53]
#### Which Note Type (and version) is this about?
IO-one by one

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.
 - [x] I've read through the README documents on this github and/or watched the tutorial video on the note types

#### What Anki version are you using?
Version ⁨2.1.49 (dc80804a)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

```
2.1.##
```

#### Your question
If I try to use an image with long height, it appear to be resized on the editing fields.
(On reviewing the cards, the images appears just as its original sizes.)
This makes me hard to make clozes on the image because of its small size.
I assume that this would be caused by "Closet for Anki" add-on.
I have tried to change the options on the add-on, but nothing changed.
Can I make the height appear just as it is on the eiditing fields?

![2022-02-21_144709](https://user-images.githubusercontent.com/97045746/154896604-29096fa6-9246-495d-9761-8722992def71.png)

![what I want](https://user-images.githubusercontent.com/97045746/154896368-2e4528d8-9018-4661-a853-8157ea82379a.png)

**Comment by Stat-Shiwoo** [comment]
I have tested when I only activated "Anking note type" and "Closet for Anki", but it didn't work. This doesn't happen only when I deactivated "Closet for Anki". And I don't have "resize images in editor"... I am using Windows 10 now, and I don't know whether the same thing happens on my mac (because I have made it repaired now)

**Comment by AnKingMed** [comment]
It could be related to the css.  See if changing any of the img max-width and max-height paraments fixes anything (or deleting them altogether)

**Comment by Stat-Shiwoo** [comment]
I have tried to change the options on CSS of "IO-one by one" : (1) deleting options related to any "image" height/width and (2) changing to "none" like "max-height : none". However nothing worked out niether. Fortunately, I found the add-on named "Maximum image height and width in card editor", and I changed its options as "none" which solved this issue. Thanks a lot !
