### ISSUE TITLE
AMBOSS add-on is disabled for words in cloze in one by one 

### ISSUE THREAD

**Issue by AH349** [AnKingMed/AnKing-Note-Types#58]
#### Which Note Type (and version) is this about?
AnKing 
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
AMBOSS addon seems to be disabled for words in cloze. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.49
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
Windows
*Please include OS version as well if possible*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Reproducible on my end.  It must have to do with the javascript that makes the IO one by one.  Thanks for reporting this
