### ISSUE TITLE
Lecture notes field max-width no longer editable with new note type

### ISSUE THREAD

**Issue by skywalkercode** [AnKingMed/AnKing-Note-Types#59]
#### Which Note Type (and version) is this about?
AnKingOverhaul
#### Problem description

Can no longer edit/change max-width of the lecture notes field. 
Previous note types had "#lecture img" in styling section to adjust max-width. 
"#lecture img" no longer appears in the new note type in either the 60% or 85% max-width code section. 
Manually adding "#lecture img" does not solve the problem either.

**Previous function**
![image](https://user-images.githubusercontent.com/80597608/156962028-d60bfae5-4142-46b7-ab63-9fca238097cb.png)

**New note type with manually added "#lecture img" does not fix**
![image](https://user-images.githubusercontent.com/80597608/156962111-a7fb7c19-aedf-41f2-b186-73610fd709fb.png)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.49
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*
Windows

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
I'm just looking on my phone but try #notes instead of #lecture

**Comment by AnKingMed** [comment]
Looked into this further and I believe it's because that field uses #notes and not #lecture. Let me know if that doesn't fix things for you

**Comment by skywalkercode** [comment]
> 

this fixed it! Thank you for the troubleshooting this. Probably should have been able to see that myself!
