### ISSUE TITLE
Help with coding

### ISSUE THREAD

**Issue by Falconview314** [AnKingMed/AnKing-Note-Types#60]
#### Which Note Type (and version) is this about?

General question

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've checked if anyone else asked this question before by looking through the issue reports.
 - [ x] I've read through the README documents on this github and/or watched the tutorial video on the note types

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.49
```

#### Your question

*A clear and concise question about the note type.*
I appreciate all that you do to help students master Anki! I was wondering if there is any way I could help out with the coding aspect of what you do? I am majoring in computer science and my premed major of chemistry and would love to practice my coding knowledge. This knowledge is very limited right now. The highlight of my coding journey is my Yahtzee python program. Don't laugh. I am currently learning Java. I can help out with mundane tasks if need be. I can create the lists or whatnot. Just looking to help out in any way possible. Thank you.

cedric.anderson618@gmail.com

**Comment by AnKingMed** [comment]
This would be awesome. Are you comfortable at all with Anki's codebase and how to make an add-on? Or more just code that would be suitable for note types like these?

**Comment by Falconview314** [comment]
You know what, that's a great idea! I just recently entered the Raspberry Pi rabbit hole, and I should practice with your card types in conjunction. I've familiarised myself with the overhaul deck because that is the main one I use, but I can assure you that I can learn the rest of them. 

Thank you for taking the time to respond as well.

**Comment by AnKingMed** [comment]
Of course! What would be helpful is to try and tackle any simple issues on here or add completely new features that won't conflict with anything currently there. Just let me know in advance so we can chat about it!  You could also create an entirely new note type :)

**Comment by Falconview314** [comment]
That sounds great. Just let me know what issues I can work (or try at least). I do have an idea for a new note type that came to mind the other day.
