### ISSUE TITLE
"Extra" not showing under Hint Buttons for Anking Overhaul note type

### ISSUE THREAD

**Issue by mangomonday01** [AnKingMed/AnKing-Note-Types#61]
#### Which Note Type (and version) is this about?
AnKingOverhaul v11

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

I am trying to hide all fields so that I do not see the extra fields when a one-by-one card auto-flips. I am able to hide all but the "extra" field because it does not exist under the "hint buttons" section for this note type. Interestingly, the extra field _is_ visible under hint buttons for the "IO one by one" note type.
**I know there is a planned update to make the extra field show up after all cloze's have been revealed, but I feel like this feature should still exist for this note type**

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x ] I've tried to disable add-ons to see if there are any interactions present
 - [_unable to configure this add on when Anki is opened while holding shift_ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using? 

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.49
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*
Mac OS Monterey 12.2

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```
<img width="855" alt="image" src="https://user-images.githubusercontent.com/102324321/159996231-b346ad9b-f693-455d-9141-4bdeaa08f641.png">
<img width="858" alt="image" src="https://user-images.githubusercontent.com/102324321/159996274-77efcc64-aa69-47b7-b906-7abf23cebcc0.png">
<img width="846" alt="image" src="https://user-images.githubusercontent.com/102324321/159996331-35f3006b-a1d6-4a24-b407-f07f4a069f12.png">

**Comment by AnKingMed** [comment]
This is a known issue. I think we'll probably have to put the Extra field under a button like everything else. Thanks for the report though

**Comment by RisingOrange** [comment]
There is a new update to the add-on that should fix this issue. A new option category named Fields was added and the option to disable buttons/fields was moved there.
