### ISSUE TITLE
general changes not being applied to any of the cards (i.e. font size, color, etc)

### ISSUE THREAD

**Issue by m0nisa** [AnKingMed/AnKing-Note-Types#68]
#### Which Note Type (and version) is this about?
AnKing Note Types (Easy Customization)
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
None of the options such as font size, style, color, etc. have been saving. When I click on update notetypes the button is unclickable and even with removing and re-adding the add on this issue still persists. I can change the features of color and size if I manually go into the card and edit the code for style but the add on seems to be just not operative. 
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*
Monterey Version 12.4

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Can you go to file-> export and choose .colpkg then upload here? Please don't include media

**Comment by m0nisa** [comment]
It seems I can't upload that file type on here...? Do I need to compress the file first or something?

**Comment by AnKingMed** [comment]
![image](https://user-images.githubusercontent.com/57678116/178109231-37575aba-79bb-4793-b72a-52e8eb06fd99.png)

It looks like your notes are all this AnKingOverhaul-883af.  You just need to click that note type in the browser, click a note, ctrl+a to select all, then do Notes->Change Note Type and change it to the "AnKingOverhaul" note type and that should fix it

**Comment by m0nisa** [comment]
That worked! Thank you!!
