### ISSUE TITLE
IO one by one not working

### ISSUE THREAD

**Issue by jc99632** [AnKingMed/AnKing-Note-Types#72]
#### Which Note Type (and version) is this about?
IO one by one
#### Problem description

My IO one by one cards were working fine previously, but now when I open them in review all of the boxes aren't visible and they won't toggle with toggle all. The card works fine in the browser, but does not function in reviews (just shows the unoccluded image when I flip the card).

Just wanted to bring this to your attention, not sure if anyone else has had this issue. I am currently on  ⁨2.1.48. on windows.

```

**Comment by AnKingMed** [comment]
This should be fixed now with the latest update
