### ISSUE TITLE
load on issue

### ISSUE THREAD

**Issue by jaffri12** [AnKingMed/AnKing-Note-Types#75]
Im on version 2.1.44 and attemping to download https://ankiweb.net/shared/info/952691989

I try to download anking note types add on, when I log in it states this and that the add on has failed to load,

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

2.1.44

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.44
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Windows

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
When loading '⁨AnKing Note Types Easy Customization⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 210, in loadAddons
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\952691989\__init__.py", line 9, in <module>
    from .gui.config_window import NotetypesConfigWindow
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\952691989\gui\config_window.py", line 52, in <module>
    class NotetypesConfigWindow:
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\952691989\gui\config_window.py", line 515, in NotetypesConfigWindow
    model: NotetypeDict,
NameError: name 'NotetypeDict' is not defined
```

**Comment by AnKingMed** [comment]
@RisingOrange

**Comment by RisingOrange** [comment]
I uploaded a new version of the add-on that fixes this to AnkiWeb.
