### ISSUE TITLE
IO-one by one bug

### ISSUE THREAD

**Issue by leo100rock** [AnKingMed/AnKing-Note-Types#76]
#### Which Note Type (and version) is this about?
Anking IO-one by one
#### Problem description

It's still a bug with the IO cards, so I tried to update the anking but I end up getting the same error message every time. I can't save the changes after I've updated and I'm still not able to use the IO cards.
The other fields work, but the omissions do not appear.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X] I've restarted Anki to see if it helps
 - [X] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [X] I've tried to disable add-ons to see if there are any interactions present
 - [X] My issue disappears when I hold shift while starting Anki.
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

```
2.1.49
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Windows 10 Pro 

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Erro
Ocorreu um erro. Por favor, inicie o Anki enquanto segura a tecla shift, isto vai desabilitar temporariamente as extensões que você instalou.
Se o problema ocorrer somente quando as extensões são habilitadas, use o Ferramentas > Extensões para desabilitar algumas extensões e reinicie o Anki, repetindo até descobrir a extensão que está causando o problema.
Quando você descobrir a extensão que está causando o problema, por favor reporte o problema em site de suporte de extensão.
Informações de Depuração:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-24 20:35:45

Caught exception:
Traceback (most recent call last):
  File "aqt\taskman.py", line 101, in _on_closures_pending
  File "aqt\taskman.py", line 71, in <lambda>
  File "aqt\taskman.py", line 90, in wrapped_done
  File "C:\Users\leona\AppData\Roaming\Anki2\addons21\952691989\gui\config_window.py", line 403, in on_done
    mw.col.models.update_dict(model)  # type: ignore
  File "anki\models.py", line 223, in update_dict
  File "anki\_backend\generated.py", line 444, in update_notetype_legacy
  File "anki\_backend\__init__.py", line 131, in _run_command
anki.errors.TemplateError: O modelo do cartão ⁨1⁩ tem um problema.<br>See the preview for more information.

```
![image](https://user-images.githubusercontent.com/109625733/180827571-59ced9a0-7e55-41ca-9088-ea5741578b32.png)
![image](https://user-images.githubusercontent.com/109625733/180826312-6d7a5d30-2d97-42bd-8e75-28ac8d8770f4.png)
![image](https://user-images.githubusercontent.com/109625733/180826392-b19a73cc-4724-490b-968a-03a102ec1e6e.png)
![image](https://user-images.githubusercontent.com/109625733/180826438-73a89ed9-cc51-44ab-ab79-2f38ad5a62dd.png)
![image](https://user-images.githubusercontent.com/109625733/180826468-6317bd37-fa0a-4a3a-9ee5-b24ccde043ec.png)
![image](https://user-images.githubusercontent.com/109625733/180827374-ea296498-0c22-4586-bb60-b3778f4ebcd5.png)
Collection without media: https://we.tl/t-ZdqXgXtXn6

**Comment by RisingOrange** [comment]
Could you please try to install the add-on again? You may have to check for updates under Tools -> Add-ons -> Check for updates for the update to appear.

**Comment by leo100rock** [comment]
![image](https://user-images.githubusercontent.com/109625733/180828962-cc1e79ff-0c20-4b86-b6a0-208a893c1e6e.png)
![image](https://user-images.githubusercontent.com/109625733/180829072-2c9ee298-c315-4bcb-9c63-067cf3d28009.png)
Got the same error.

**Comment by AnKingMed** [comment]
I just downloaded @leo100rock 's collection and wasn't able to reproduce the error on 2.1.54qt5.  @leo100rock maybe try deleting the add-on and redownloading and then restarting

**Comment by leo100rock** [comment]
I ended up removing some extensions and reinstalling Anking, as you suggested @AnKingMed @RisingOrange , and it worked again. Thanks and Thanks for listening!
