### ISSUE TITLE
New AnKing Overhaul note types in AnkiHub are not reflected as options in the add-on

### ISSUE THREAD

**Issue by dollajas** [AnKingMed/AnKing-Note-Types#85]
Running Anki 2.1.54 with updated note types add-on. In a new profile with the AnkiHub set up, the note types add on does not recognize the AnKingOverhaul (AnKing / AnKingMed) note type - saying there are no matching note types in the collection

Video displaying error: https://imgur.com/a/CLb9h3w

**Comment by AnKingMed** [comment]
Try importing. Maybe it needs the main type too

**Comment by dollajas** [comment]
That was it, pretty confusing. Had to import the regular note type and modify that to have the other note type changes take effect.

Best,

Abdulla Jastaniah
VCOM-VA | Class of 2023
(703) 608-6172
***@***.***
