### ISSUE TITLE
IO One by One Error on qt5

### ISSUE THREAD

**Issue by cwmschmidty** [AnKingMed/AnKing-Note-Types#86]
Hi, 

Have tried editing an existing card to IO one by one and also creating new one. I receive this error when I hit add new card. When I close the error I can add the card but there is no IO on the card in preview or if I set the card to due. Also, the IO one by one example card also doesn't work. 

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-08-20 02:20:17

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "aqt.editor", line 561, in <lambda>
  File "aqt.addcards", line 259, in _add_current_note
  File "aqt.addcards", line 294, in _note_can_be_added
  File "aqt.hooks_gen", line 172, in __call__
  File "C:\Users\J\AppData\Roaming\Anki2\addons21\272311064\src\addcards.py", line 18, in check_if_occlusion_editor_open
    if addcards.editor.occlusion_editor_active
AttributeError: 'NoneType' object has no attribute 'editor'

**Comment by AnKingMed** [comment]
This is the closet addon. Can you report it on that GitHub?

**Comment by cwmschmidty** [comment]
Will do, thanks!

**Comment by cwmschmidty** [comment]
Hi @AnKingMed,

I figured out the problem but just want to check if it's closet or the note type. When I open manage note types and choose IO-one by one I realized the note type is using closet 0.5.3 whereas closet is on 0.6.1 right now. When I open asset manager and write changes to the card type it now works. However, it then tells me from the anking note type manager that my cards are outdated. So every time the cards update then they stop working.

**Comment by AnKingMed** [comment]
@RisingOrange can you look into this and see what we need to do to update the note type for the add-on?   That note type was also shipped with the AnKing deck in AnkiHub so we should consider that as well

**Comment by AnKingMed** [comment]
@BlueGreenMagick  if you have time to address this that'd be great too. 

We should try to make the note type support both if possible..

**Comment by AnKingMed** [comment]
@cwmschmidty I just tested our latest note type with the latest closet add-on (I didn't change anything to the IO-one by one note type) and it's working fine for adding new cards. Maybe try deleting the closet add-on and then reinstalling?

**Comment by cwmschmidty** [comment]
@AnKingMed I deleted both the closet add-on and the asset manager and when I opened anki back up my IO-one by one cards still worked. When I updated the notetype using the anking note types add on they stopped working. I then reinstalled the closet add-on it still didn't work. Adding the asset manager add-on back in and then using that to "write to template" gets them working again. Whatever the change in the asset manager does is bring the closet add-on from 0.5.3 to 0.6.1.

**Comment by AnKingMed** [comment]
Maybe try everything with the asset manager off the whole time. I don't even have that addon installed at the moment. Just the up to date IO one by one note type and the latest closet add-on on 2.1.54 Qt5

**Comment by cwmschmidty** [comment]
@AnKingMed I deleted both at the beginning. Then only added the closet add-on first. Updated the note type and it still didn't work. 
![image](https://user-images.githubusercontent.com/58187956/185810567-2953df7f-5df7-4018-9d93-30f387512abf.png)

This is what I see even with the asset manager removed when I click the closet button in the "manage note type" section.

**Comment by cwmschmidty** [comment]
![image](https://user-images.githubusercontent.com/58187956/185810651-2a251f19-bb9b-4031-98ac-c996ebdf8730.png)

Looking in the back template of the IO one by one card this is what I found.

![image](https://user-images.githubusercontent.com/58187956/185810680-398f77cc-94f4-4f73-ab90-b798232fdd91.png)

And here is the anking note type add on showing my notetypes are updated

**Comment by AnKingMed** [comment]
That's what I see too, but the note type works fine for me.

Can you ensure that you're making note types the same way: https://jmp.sh/HAKSedV

**Comment by cwmschmidty** [comment]
![io test](https://user-images.githubusercontent.com/58187956/185811103-ec0ffd5e-7906-415a-b1d3-5d7257a99ba0.gif)

Now clicking the closet cloze doesn't even put a red box around the image anymore.

**Comment by cwmschmidty** [comment]
Tried to make a screen recording but wasn't working. Now trying to make cards I don't get the red box around the image. But that's how I was making them before.

**Comment by cwmschmidty** [comment]
Going to preview in card browser, the cards don't work either.

**Comment by AnKingMed** [comment]
If you're able to make a screen recording that'd be really helpful.  Quicktime and jump share are pretty useful for screen recordings

**Comment by cwmschmidty** [comment]
https://1drv.ms/v/s!Aof_PMwlICT4t1oDCrDjpFf43E-v?e=HGe52U

I made a screen recording but the file was too big to upload. I put the video in my onedrive.

**Comment by AnKingMed** [comment]
That is odd. But upgrading the closet in manage note types fixes the problem? If that's the case I can look into doing that for the note types on the addon as it's an easy change

**Comment by cwmschmidty** [comment]
The only thing that fixes it on my end is adding the "asset manager" add on. Then in manage note types I select IO one by one and click assets. After selecting write to template it starts working again. However, it tells me my note types need to be updated after this.

**Comment by cwmschmidty** [comment]
After using the asset manager to update the note type it changes the IO one by one card template from having 0.5.3 in it to 0.6.1.

**Comment by cwmschmidty** [comment]
thank you!
