### ISSUE TITLE
IO one by one not creating any cards

### ISSUE THREAD

**Issue by serfatyable** [AnKingMed/AnKing-Note-Types#89]
#### Which Note Type (and version) is this about?
image occlusion one by one
#### Problem description
Not creating any occlusions
*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
I watched the video, downloaded the most recent version of the card and the closet add on, followed all the steps. still, when creating a card, while reviewing, i don't see any occlusions, the picture just appears naked. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
qt6 but I tried it in qt5 and it's the same
*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
linux
*Please include OS version as well if possible*

ubuntu
#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Can you try disabling the clickable tags addon?

**Comment by serfatyable** [comment]
yeah that worked !

**Comment by AnKingMed** [comment]
Can you export a copy of your IO one by one note?  I've been unable to recreate this conflict

**Comment by serfatyable** [comment]
recent:///094e1ee894c69c5942d554806318ea01

**Comment by serfatyable** [comment]
sure here it is:
https://drive.google.com/file/d/1xnGwEuGy8CJHoBKTFcqfj2oNNIDbjT6i/view?usp=sharing

**Comment by AnKingMed** [comment]
I requested access. You can zip the file and drag and drop it here as well

**Comment by serfatyable** [comment]
Oh sorry, whole different time zone, I granted Access now

**Comment by AnKingMed** [comment]
Looks like if you reset the note type in the AnKing Note Types add-on config, it starts working again with the IO one by one note type
