### ISSUE TITLE
Red Exclamation points in review

### ISSUE THREAD

**Issue by LucasFrench** [AnKingMed/AnKing-Note-Types#91]
[####]([url](url)) Which Note Type (and version) is this about?

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

After beginning a review session in a deck, all of the cards with the "AnKingOverhaul (AnKing/AnKingMed)" note type display red exclamation points down the lower, center portion of the card. These appear before hitting the spacebar, and only when I move the mouse after a new card pops up. If I never move the mouse or hit a button, they never appear.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*

macOS Monterey
Version 12.5.1
MacBook Pro (14-inch, 2021)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
<img width="1512" alt="Screen Shot 2022-09-15 at 8 43 54 PM" src="https://user-images.githubusercontent.com/29283494/190539668-c495fa8c-a981-4f1b-abbd-97db628f0119.png">

```

**Comment by AnKingMed** [comment]
This is a feature. You can see it [here](https://github.com/AnKingMed/AnKing-Note-Types/blob/master/README.md#features-used-in-these-note-types) as the "invisible countdown timer". It can be toggled off with the Note Types Add-on

See this tutorial video: https://youtu.be/NYUhNMyAZNs
