### ISSUE TITLE
Easy Conversion of Image Occlusion Enhanced to IO One by One

### ISSUE THREAD

**Issue by cwmschmidty** [AnKingMed/AnKing-Note-Types#94]
Working through some non anking cards in one of my schools premade decks I have been changing many cards from Image Occlusion Enhanced to IO One by One. However the templates don't line up to get the correct material transferred over.

![anki_Fy8UsjPTG7](https://user-images.githubusercontent.com/58187956/195006141-8627982e-c2fe-40a4-8d9f-e1dd36638870.png)

I currently created a note type that acts as an intermediate in this process:

![anki_5frrllSzbc](https://user-images.githubusercontent.com/58187956/195006427-161e3f84-deb4-40d2-8e3e-774fef8ba154.png)

So I can then convert it from IO enhanced to IO one by one:

![anki_sXxCryj45F](https://user-images.githubusercontent.com/58187956/195006481-45ca09ca-1a58-4e7d-9a2a-5a9e11c71725.png)

An ability to create card conversions template would make it so much easier to update old lecture material to this much better note type. I get this is a niche request and I have found a workaround but I was thinking other people might have the problem and/or benefit from a solution.

**Comment by AnKingMed** [comment]
You can't change Image Occlusion to IO one by one. They're fundamentally different so they can't be converted
