### ISSUE TITLE
Amboss Add-on and one by one cloze with the ankingoverhaul notetype.

### ISSUE THREAD

**Issue by cwmschmidty** [AnKingMed/AnKing-Note-Types#95]
Ankingoverhaul and the one by one field.

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ x] I've checked if anyone else asked this question before by looking through the issue reports.
 - [x ] I've read through the README documents on this github and/or watched the tutorial video on the note types

QT5 What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Your question

Hi, sorry it's me again. I've noticed that any words that get put in a one by one format from the ankingoverhaul note type that the amboss add on doesn't recognize that text for reference from their resource. Not sure if this is an amboss issue, anking note type issue, or something on my end. Has anyone on your end run into this problem?

**Comment by AnKingMed** [comment]
Oh interesting. I'll have to test this out and see what's going on

**Comment by cwmschmidty** [comment]
any update on this?

**Comment by AnKingMed** [comment]
Haven't had time to look into it sorry. Might be worth asking AMBOSS about it. 

@BlueGreenMagick if you have time you could look into this

**Comment by BlueGreenMagick** [comment]
Basically, the AMBOSS add-on looks for the words when the card side first loads, but at that time the words are 'hidden' so it's not detected.

I don't think the AMBOSS api for detecting phrases is exposed, so we'll probably want to put the original words in a 'display:none' span and show/hide it. 

I'll work on this next
