### ISSUE TITLE
IO 1 by 1 notes don't work when using label feature

### ISSUE THREAD

**Issue by MightyBooman** [AnKingMed/AnKing-Note-Types#96]
#### Problem description

When creating a new note using the IO 1 by 1 note type, if you right click on an occlusion and select 'Change Label', then the note will not work properly in review.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ x] I've tried to disable add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

MacOS Monterey 12.6

#### Error message (if any)

n/a

```

```

**Comment by MightyBooman** [comment]
Attached are a handful of notes I made today which led to me finding the bug

[IO issue.apkg.zip](https://github.com/AnKingMed/AnKing-Note-Types/files/9824039/IO.issue.apkg.zip)

**Comment by AnKingMed** [comment]
This is probably more appropriate to report on the Closet Add-on. Can you share it there?
