### ISSUE TITLE
Language note type TTS 

### ISSUE THREAD

**Issue by fightingsoul79** [AnKingMed/AnKing-Note-Types#97]
I'm learning Russian with the help of Anki. Naturally, I would like to hear the pronunciation of every new term I come across.
Here's the problem.
My native OS is pronouncing Russian words in American English.
I tried everything, I even changed the language to Russian, but it's not working. 
I don't face this problem when I'm listening to highlighted text outside of Anki, even when the language is set to English.
How can I fix this issue?

**Comment by AnKingMed** [comment]
Is this specific to the AnKing Note Type?  This is a question probably better suited for forums.ankiweb.net

**Comment by fightingsoul79** [comment]
Alright, thank you! I'll ask there! :)
